### ISSUE TITLE
Don't know where to find the 2 API keys 

### ISSUE THREAD

**Issue by bochenn** [omgwtfwow/segment-for-wp-by-in8-io#1]
Hi Juan!

Thanks for this great plugin!

I see your plugin asks for 2 API keys but in Segment I'm only getting 1. Please see the following screenshots.

https://www.dropbox.com/s/nf0k516trxktih2/Screen%20Shot%202021-09-29%20at%2015.32.27.png?dl=0
https://www.dropbox.com/s/3sjgv1aeg1tq31w/Screen%20Shot%202021-09-29%20at%2015.33.53.png?dl=0

Can you please advise on this?

Thanks,
L

**Comment by omgwtfwow** [comment]
Hi, the minimum you need is the JS source.

For the second key, you need to create a [**PHP source**](https://app.segment.com/tomwaterhouse/sources/catalog/php) in Segment and use the write key it gives you.

It will provide you a php write key.

Hope that helps.
