### ISSUE TITLE
Analytics not defined errors when using User Role Filtering

### ISSUE THREAD

**Issue by axertion** [omgwtfwow/segment-for-wp-by-in8-io#11]
If you use the Filtering feature to exclude certain roles, you get a frontend JS error because the client-side *Page* events still fire, but the Analytics JS isn't loaded

![image](https://user-images.githubusercontent.com/617549/144679027-a9a251b0-9dc2-422f-a91e-3a97db7e61a8.png)

![image](https://user-images.githubusercontent.com/617549/144678969-cc62e0d9-f304-45b3-9833-b09b911c54ec.png)

This is because the Page class always trys to call the `analytics.page()`, but the main script is excluded from loading if the identified user isn't trackable.

I created a PR to fix this here:
https://github.com/omgwtfwow/segment-for-wp-by-in8-io/pull/10/files

**Comment by omgwtfwow** [comment]
Cheers, merged.
Will include in next release.
