### ISSUE TITLE
Does it work with a cache plugin ?

### ISSUE THREAD

**Issue by razvanFrandes** [omgwtfwow/segment-for-wp-by-in8-io#16]
Hello,

Thank you for the plugin. I can't seem to find any information on the web if segment works if the pages are cached. Maybe it works only with object cache.

Thank you

**Comment by omgwtfwow** [comment]
It should work, don't see why not.

I suppose you could have an issue will if your analytics.js file is cached, and then you make changes in Segment (like adding a new destination that requires a new bundle of analytics.js).

In that case you might need to clear the cache.

I'm probably not the best person to answer these tho, probably [best to ask here](https://github.com/segmentio/analytics-next).
